/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ans.paintbrush;

import java.awt.Color;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class PropertyPanel extends javax.swing.JPanel {
    
    private Map<String,Object> allProperties;

    /** Creates new form PropertyPanel */
    public PropertyPanel() {
        initComponents();
           
//        this.propertyJTable1.addRow("Filled", new Boolean(true));
//        this.propertyJTable1.addRow("Today", new Date());
//        this.propertyJTable1.addRow("Today", new String());
//        this.propertyJTable1.addRow("Today", new Integer(0));
//        this.propertyJTable1.addRow("Today", new String[]{"Ahmed","Mohamed"});
//        this.propertyJTable1.addRow("Color", Color.yellow);
//        this.propertyJTable1.addRow("Color", new PropertyJTable.MiniMaxInt(5,1,100,1));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        propertyJTable1 = new ans.paintbrush.PropertyJTable();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(propertyJTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private ans.paintbrush.PropertyJTable propertyJTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the allProperties
     */
    public Map<String,Object> getAllProperties() {
        return allProperties;
    }

    /**
     * @param allProperties the allProperties to set
     */
    public void setAllProperties(Map<String,Object> allProperties) {
        this.allProperties = allProperties;
        
        updateGuI();
    }
    
    
    private  void updateGuI(){
//        jPanel1.removeAll();
//        jPanel1.add(jLabel1);
//        jPanel1.add(jLabel2);
//
//        Set<String>keys= allProperties.keySet();
//        
//        for(String key : keys)
//        {
//        String val=allProperties.get(key);
//        jPanel1.add(new JLabel(key));
//        jPanel1.add(new JTextField(val));
//       
//        }
//        System.out.println(allProperties);
//        jPanel1.repaint();
//        jPanel1.revalidate();
//        jPanel1.doLayout();
//        
    }

}
