/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ans.paintbrush;

import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ToolsPanel extends javax.swing.JPanel {

    private boolean drawing = true;
    private Color Color;

    /**
     * Creates new form ToolsPanel
     */
    public ToolsPanel() {
        initComponents();
//        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SimplePanel = new javax.swing.JPanel();
        ComplexPanel = new javax.swing.JPanel();
        QNumFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        numQ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numAns = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        TextFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldText = new javax.swing.JTextField();
        ok1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        buttons = new javax.swing.JPanel();
        jToggleButtonLine = new javax.swing.JToggleButton();
        jToggleButtonCertain = new javax.swing.JToggleButton();
        jToggleButtonRect = new javax.swing.JToggleButton();
        jToggleButtonRoundRect = new javax.swing.JToggleButton();
        jToggleButtonRightTriangle = new javax.swing.JToggleButton();
        jToggleButtonTriangle = new javax.swing.JToggleButton();
        jToggleButtonCircle = new javax.swing.JToggleButton();
        jToggleButtonOval = new javax.swing.JToggleButton();
        jToggleButtonHexognal = new javax.swing.JToggleButton();
        jToggleButtonpantagram = new javax.swing.JToggleButton();
        jToggleButtonStar = new javax.swing.JToggleButton();
        jToggleButtonSixPointStar = new javax.swing.JToggleButton();
        jToggleButtonRight = new javax.swing.JToggleButton();
        jToggleButtonLeft = new javax.swing.JToggleButton();
        jToggleButtonUp = new javax.swing.JToggleButton();
        jToggleButtonDown = new javax.swing.JToggleButton();
        jToggleButtonSmile = new javax.swing.JToggleButton();
        jToggleButtonText = new javax.swing.JToggleButton();
        jPanelNorth = new javax.swing.JPanel();
        jPanelSouth = new javax.swing.JPanel();
        jPanelEast = new javax.swing.JPanel();
        jPanelWest = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxFillColor = new javax.swing.JCheckBox();
        jButtonChooseColor = new javax.swing.JButton();
        jToggleButtonSelect = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonQBlock = new javax.swing.JButton();
        jButtonSeatNumber = new javax.swing.JButton();

        SimplePanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        ComplexPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        QNumFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        QNumFrame.setTitle("Create Question Block");
        QNumFrame.setLocationByPlatform(true);
        QNumFrame.setMinimumSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Question number");

        jLabel2.setText("Answer number");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numQ, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(numAns))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok)
                .addGap(48, 48, 48)
                .addComponent(cancel)
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(ok))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        QNumFrame.getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        TextFrame.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Text:");

        jTextFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextActionPerformed(evt);
            }
        });

        ok1.setText("OK");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        cancel1.setText("Cancel");
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jTextFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(ok1)
                        .addGap(48, 48, 48)
                        .addComponent(cancel1)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel1)
                    .addComponent(ok1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        TextFrame.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        buttons.setBackground(new java.awt.Color(255, 255, 255));
        buttons.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        buttonGroup1.add(jToggleButtonLine);
        jToggleButtonLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/diagonal-line.png"))); // NOI18N
        jToggleButtonLine.setSelected(true);
        jToggleButtonLine.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonLineStateChanged(evt);
            }
        });
        jToggleButtonLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLineActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonLine);

        buttonGroup1.add(jToggleButtonCertain);
        jToggleButtonCertain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/diamond.png"))); // NOI18N
        jToggleButtonCertain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonCertainStateChanged(evt);
            }
        });
        jToggleButtonCertain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCertainActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonCertain);

        buttonGroup1.add(jToggleButtonRect);
        jToggleButtonRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rectangle18.png"))); // NOI18N
        jToggleButtonRect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonRectStateChanged(evt);
            }
        });
        jToggleButtonRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRectActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonRect);

        buttonGroup1.add(jToggleButtonRoundRect);
        jToggleButtonRoundRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rounded-rectangle18.png"))); // NOI18N
        jToggleButtonRoundRect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonRoundRectStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonRoundRect);

        buttonGroup1.add(jToggleButtonRightTriangle);
        jToggleButtonRightTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right-triangle.png"))); // NOI18N
        jToggleButtonRightTriangle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonRightTriangleStateChanged(evt);
            }
        });
        jToggleButtonRightTriangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRightTriangleActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonRightTriangle);

        buttonGroup1.add(jToggleButtonTriangle);
        jToggleButtonTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bleach.png"))); // NOI18N
        jToggleButtonTriangle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonTriangleStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonTriangle);

        buttonGroup1.add(jToggleButtonCircle);
        jToggleButtonCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dry-clean.png"))); // NOI18N
        jToggleButtonCircle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonCircleStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonCircle);

        buttonGroup1.add(jToggleButtonOval);
        jToggleButtonOval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ellipse.png"))); // NOI18N
        jToggleButtonOval.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonOvalStateChanged(evt);
            }
        });
        jToggleButtonOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOvalActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonOval);

        buttonGroup1.add(jToggleButtonHexognal);
        jToggleButtonHexognal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/polygon.png"))); // NOI18N
        jToggleButtonHexognal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonHexognalStateChanged(evt);
            }
        });
        jToggleButtonHexognal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonHexognalActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonHexognal);

        buttonGroup1.add(jToggleButtonpantagram);
        jToggleButtonpantagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pentagon-.png"))); // NOI18N
        jToggleButtonpantagram.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonpantagramStateChanged(evt);
            }
        });
        jToggleButtonpantagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonpantagramActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonpantagram);

        buttonGroup1.add(jToggleButtonStar);
        jToggleButtonStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star (1).png"))); // NOI18N
        jToggleButtonStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonStarStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonStar);

        buttonGroup1.add(jToggleButtonSixPointStar);
        jToggleButtonSixPointStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.png"))); // NOI18N
        jToggleButtonSixPointStar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonSixPointStarStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonSixPointStar);

        buttonGroup1.add(jToggleButtonRight);
        jToggleButtonRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right.png"))); // NOI18N
        jToggleButtonRight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonRightStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonRight);

        buttonGroup1.add(jToggleButtonLeft);
        jToggleButtonLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        jToggleButtonLeft.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonLeftStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonLeft);

        buttonGroup1.add(jToggleButtonUp);
        jToggleButtonUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/up-arrow.png"))); // NOI18N
        jToggleButtonUp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonUpStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonUp);

        buttonGroup1.add(jToggleButtonDown);
        jToggleButtonDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/down-arrow.png"))); // NOI18N
        jToggleButtonDown.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonDownStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonDown);

        buttonGroup1.add(jToggleButtonSmile);
        jToggleButtonSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/smile.png"))); // NOI18N
        jToggleButtonSmile.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonSmileStateChanged(evt);
            }
        });
        buttons.add(jToggleButtonSmile);

        buttonGroup1.add(jToggleButtonText);
        jToggleButtonText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/text.png"))); // NOI18N
        jToggleButtonText.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonTextStateChanged(evt);
            }
        });
        jToggleButtonText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonTextActionPerformed(evt);
            }
        });
        buttons.add(jToggleButtonText);

        jPanel6.add(buttons, java.awt.BorderLayout.CENTER);

        jPanelNorth.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNorth.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanelNorth, java.awt.BorderLayout.WEST);

        jPanelSouth.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSouth.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanelSouth, java.awt.BorderLayout.WEST);

        jPanelEast.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEast.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelEastLayout = new javax.swing.GroupLayout(jPanelEast);
        jPanelEast.setLayout(jPanelEastLayout);
        jPanelEastLayout.setHorizontalGroup(
            jPanelEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelEastLayout.setVerticalGroup(
            jPanelEastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.add(jPanelEast, java.awt.BorderLayout.WEST);

        jPanelWest.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWest.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanelWestLayout = new javax.swing.GroupLayout(jPanelWest);
        jPanelWest.setLayout(jPanelWestLayout);
        jPanelWestLayout.setHorizontalGroup(
            jPanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanelWestLayout.setVerticalGroup(
            jPanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jPanel6.add(jPanelWest, java.awt.BorderLayout.WEST);

        add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jCheckBoxFillColor.setText("Fill Color");
        jCheckBoxFillColor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxFillColorStateChanged(evt);
            }
        });
        jCheckBoxFillColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFillColorActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBoxFillColor);

        jButtonChooseColor.setText("Choose Color");
        jButtonChooseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseColorActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonChooseColor);

        buttonGroup1.add(jToggleButtonSelect);
        jToggleButtonSelect.setText("Select");
        jToggleButtonSelect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButtonSelectStateChanged(evt);
            }
        });
        jPanel4.add(jToggleButtonSelect);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);

        jButtonQBlock.setText("Create Question Block");
        jButtonQBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQBlockActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonQBlock);

        jButtonSeatNumber.setText("Create Seat Number");
        jButtonSeatNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeatNumberActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSeatNumber);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonLineActionPerformed

    private void jToggleButtonOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonOvalActionPerformed

    private void jToggleButtonOvalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonOvalStateChanged
        // TODO add your handling code here:
        if (jToggleButtonOval.isSelected()) {
            setSelectedShape(ShapesEnum.OVAL);
        }

    }//GEN-LAST:event_jToggleButtonOvalStateChanged

    private void jToggleButtonRoundRectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonRoundRectStateChanged
        // TODO add your handling code here:
        if (jToggleButtonRoundRect.isSelected())
            setSelectedShape(ShapesEnum.ROUND_RECT);
    }//GEN-LAST:event_jToggleButtonRoundRectStateChanged

    private void jToggleButtonCircleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonCircleStateChanged
        // TODO add your handling code here:
        if (jToggleButtonCircle.isSelected())
            setSelectedShape(ShapesEnum.CIRCLE);
    }//GEN-LAST:event_jToggleButtonCircleStateChanged

    private void jToggleButtonRectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonRectStateChanged
        // TODO add your handling code here:
        if (jToggleButtonRect.isSelected())
            setSelectedShape(ShapesEnum.RECTANGLE);
    }//GEN-LAST:event_jToggleButtonRectStateChanged

    private void jToggleButtonLineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonLineStateChanged
        // TODO add your handling code here:
        if (jToggleButtonLine.isSelected())
            setSelectedShape(ShapesEnum.LINE);
    }//GEN-LAST:event_jToggleButtonLineStateChanged

    private void jToggleButtonRightTriangleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonRightTriangleStateChanged
        // TODO add your handling code here:
        if (jToggleButtonRightTriangle.isSelected())
            setSelectedShape(ShapesEnum.RightTriangle);
    }//GEN-LAST:event_jToggleButtonRightTriangleStateChanged

    private void jToggleButtonRightTriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRightTriangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonRightTriangleActionPerformed

    private void jToggleButtonTriangleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonTriangleStateChanged
        // TODO add your handling code here:
        if (jToggleButtonTriangle.isSelected())
            setSelectedShape(ShapesEnum.Triangle);
    }//GEN-LAST:event_jToggleButtonTriangleStateChanged

    private void jToggleButtonHexognalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonHexognalStateChanged
        // TODO add your handling code here:
        if (jToggleButtonHexognal.isSelected()) {
            setSelectedShape(ShapesEnum.Hexognal);
        }

    }//GEN-LAST:event_jToggleButtonHexognalStateChanged

    private void jToggleButtonHexognalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonHexognalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonHexognalActionPerformed

    private void jToggleButtonSmileStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonSmileStateChanged
        // TODO add your handling code here:
        if (jToggleButtonSmile.isSelected()) {
            setSelectedShape(ShapesEnum.Smile);
        }


    }//GEN-LAST:event_jToggleButtonSmileStateChanged

    private void jToggleButtonpantagramStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonpantagramStateChanged
        // TODO add your handling code here:
        if (jToggleButtonpantagram.isSelected())
            setSelectedShape(ShapesEnum.pentagram);
    }//GEN-LAST:event_jToggleButtonpantagramStateChanged

    private void jToggleButtonCertainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonCertainStateChanged
        // TODO add your handling code here:
        if (jToggleButtonCertain.isSelected())
            setSelectedShape(ShapesEnum.Certain);
    }//GEN-LAST:event_jToggleButtonCertainStateChanged

    private void jToggleButtonStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonStarStateChanged
        // TODO add your handling code here:
        if (jToggleButtonStar.isSelected())
            setSelectedShape(ShapesEnum.Star);
    }//GEN-LAST:event_jToggleButtonStarStateChanged

    private void jToggleButtonSixPointStarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonSixPointStarStateChanged
        // TODO add your handling code here:
        if (jToggleButtonSixPointStar.isSelected())
            setSelectedShape(ShapesEnum.SixPointStar);
    }//GEN-LAST:event_jToggleButtonSixPointStarStateChanged

    private void jToggleButtonRightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonRightStateChanged
        // TODO add your handling code here:
        if (jToggleButtonRight.isSelected())
            setSelectedShape(ShapesEnum.Right);
    }//GEN-LAST:event_jToggleButtonRightStateChanged

    private void jToggleButtonLeftStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonLeftStateChanged
        // TODO add your handling code here:
        if (jToggleButtonLeft.isSelected())
            setSelectedShape(ShapesEnum.Left);
    }//GEN-LAST:event_jToggleButtonLeftStateChanged

    private void jToggleButtonUpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonUpStateChanged
        // TODO add your handling code here:
        if (jToggleButtonUp.isSelected())
            setSelectedShape(ShapesEnum.Up);
    }//GEN-LAST:event_jToggleButtonUpStateChanged

    private void jToggleButtonDownStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonDownStateChanged
        // TODO add your handling code here:
        if (jToggleButtonDown.isSelected())
            setSelectedShape(ShapesEnum.Down);
    }//GEN-LAST:event_jToggleButtonDownStateChanged

    private void jToggleButtonSelectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonSelectStateChanged
        // TODO add your handling code here:
        if (jToggleButtonSelect.isSelected())
            drawing = false;
        else
            drawing = true;
    }//GEN-LAST:event_jToggleButtonSelectStateChanged

    private void jCheckBoxFillColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFillColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFillColorActionPerformed

    private void jCheckBoxFillColorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxFillColorStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFillColorStateChanged

    private void jButtonQBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQBlockActionPerformed
        // TODO add your handling code here:

        QNumFrame.show();
    }//GEN-LAST:event_jButtonQBlockActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        QNumFrame.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        Question qshape = new Question();
//        qshape.setSelected(true);
        qshape.setqNum(Integer.parseInt(numQ.getText()));
        qshape.setAnsNum(Integer.parseInt(numAns.getText()));
        qshape.setPoints(new Point(100, 100));
        drawPanel.allShapes.add(qshape);
        drawPanel.repaint();
        
        qshape=null;
        drawPanel.currentShape=null;

        QNumFrame.dispose();
        numQ.setText("");
        numAns.setText("");

    }//GEN-LAST:event_okActionPerformed

    private void jToggleButtonpantagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonpantagramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonpantagramActionPerformed

    private void jToggleButtonTextStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButtonTextStateChanged
        // TODO add your handling code here:
        if (jToggleButtonText.isSelected())
            setSelectedShape(ShapesEnum.TEXT);
    }//GEN-LAST:event_jToggleButtonTextStateChanged

    private void jToggleButtonCertainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCertainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCertainActionPerformed

    private void jToggleButtonRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonRectActionPerformed

    private void jToggleButtonTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonTextActionPerformed

    private void jTextFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTextActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ok1ActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        // TODO add your handling code here:
        TextFrame.dispose();
    }//GEN-LAST:event_cancel1ActionPerformed

    private void jButtonSeatNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeatNumberActionPerformed
        // TODO add your handling code here:
        SeatNumber sn = new SeatNumber();
//        qshape.setSelected(true);
        sn.setPoints(new Point(350, 100));
        drawPanel.allShapes.add(sn);
        drawPanel.repaint();
        
        sn=null;
    }//GEN-LAST:event_jButtonSeatNumberActionPerformed

    private void jButtonChooseColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseColorActionPerformed
        // TODO add your handling code here:
        JColorChooser selectColor = new JColorChooser();
        Color myColor = selectColor.showDialog(null, "Select a color", Color);
        selectedColor = myColor;
    }//GEN-LAST:event_jButtonChooseColorActionPerformed

    /*
    CompositeShape cshape = new CompositeShape();
            cshape.setSelected(true);
            cshape.addAll(SelectedShapes);
            allShapes.removeAll(SelectedShapes);
            for (Shape s : SelectedShapes) {
                s.setSelected(false);
            }
            deSelectAllShapes();
            allShapes.add(cshape);
            repaint();
     */
    private Color selectedColor;
    private ShapesEnum selectedShape = ShapesEnum.LINE;
    //private Shape currentShape = null;
    private DrawPanel drawPanel;
//    private String text;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComplexPanel;
    private javax.swing.JFrame QNumFrame;
    private javax.swing.JPanel SimplePanel;
    private javax.swing.JFrame TextFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel buttons;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton jButtonChooseColor;
    private javax.swing.JButton jButtonQBlock;
    private javax.swing.JButton jButtonSeatNumber;
    private javax.swing.JCheckBox jCheckBoxFillColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelEast;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JPanel jPanelWest;
    private javax.swing.JTextField jTextFieldText;
    private javax.swing.JToggleButton jToggleButtonCertain;
    private javax.swing.JToggleButton jToggleButtonCircle;
    private javax.swing.JToggleButton jToggleButtonDown;
    private javax.swing.JToggleButton jToggleButtonHexognal;
    private javax.swing.JToggleButton jToggleButtonLeft;
    private javax.swing.JToggleButton jToggleButtonLine;
    private javax.swing.JToggleButton jToggleButtonOval;
    private javax.swing.JToggleButton jToggleButtonRect;
    private javax.swing.JToggleButton jToggleButtonRight;
    private javax.swing.JToggleButton jToggleButtonRightTriangle;
    private javax.swing.JToggleButton jToggleButtonRoundRect;
    private javax.swing.JToggleButton jToggleButtonSelect;
    private javax.swing.JToggleButton jToggleButtonSixPointStar;
    private javax.swing.JToggleButton jToggleButtonSmile;
    private javax.swing.JToggleButton jToggleButtonStar;
    private javax.swing.JToggleButton jToggleButtonText;
    private javax.swing.JToggleButton jToggleButtonTriangle;
    private javax.swing.JToggleButton jToggleButtonUp;
    private javax.swing.JToggleButton jToggleButtonpantagram;
    private javax.swing.JTextField numAns;
    private javax.swing.JTextField numQ;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the selectedShape
     */
    public ShapesEnum getSelectedShape() {
        return selectedShape;
    }

    /**
     * @param selectedShape the selectedShape to set
     */
    public void setSelectedShape(ShapesEnum selectedShape) {
        this.selectedShape = selectedShape;
    }

    public Color getCurrentColor() {
        return selectedColor;
    }

    public boolean isFilledcolor() {
        return this.jCheckBoxFillColor.isSelected();
    }

    /**
     * @return the drawing
     */
    public boolean isDrawing() {
        return drawing;
    }

    /**
     * @param drawing the drawing to set
     */
    public void setDrawing(boolean drawing) {
        this.drawing = drawing;
    }

//    private void execute() {
//        //crearSubMenuSimple
//        MenuItem SimpleMenu = new MenuItem("Simple Shapes", SimplePanel);
//        MenuItem ComplexMenu = new MenuItem("Complex Shapes", ComplexPanel);
//        addMenu(SimpleMenu, ComplexMenu);
//    }

//    private void addMenu(MenuItem... menu) {
//        for (int i = 0; i < menu.length; i++) {
//            Menu.add(menu[i]);
//            ArrayList<JPanel> subMenu = menu[i].getSubMenu();
//            for (JPanel m : subMenu) {
//                Menu.add(m);
//            }
//        }
//        Menu.revalidate();
//    }

    /**
     * @return the drawPanel
     */
    public DrawPanel getDrawPanel() {
        return drawPanel;
    }

    /**
     * @param drawPanel the drawPanel to set
     */
    public void setDrawPanel(DrawPanel drawPanel) {
        this.drawPanel = drawPanel;
    }

}
